#!/bin/sh
### BEGIN INIT INFO
# Provides:          iqfeed
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The IQFeed market data feed
# Description:       Unofficial init script for DTN IQFeed
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=iqfeed
DESC="DTN IQFeed market data feed"
LOG1=/var/log/iqfeed.log
LOG2=/var/log/iqfeed.admin.log

touch $LOG1 $LOG2
chown iqfeed $LOG1 $LOG2

# Defaults - don't touch, edit /etc/default/iqfeed or /etc/iqfeed.conf
ENABLED=0
OPTIONS=""

test -f /etc/default/$NAME && . /etc/default/$NAME
             
#test "$ENABLED" != "0" || exit 0

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon --start --name iqconnect.exe \
            --background \
            --user iqfeed \
            --chuid iqfeed:nogroup \
            --startas "/usr/lib/iqfeed/run-iqfeed"
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon --stop --name 'iqconnect.exe' 
        echo "$NAME."
        ;;
  restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon --stop --name 'iqconnect.exe' 
        start-stop-daemon --start --name iqconnect.exe \
            --background \
            --user iqfeed \
            --chuid iqfeed:nogroup \
            --startas "/usr/lib/iqfeed/run-iqfeed"
        echo "$NAME."
        ;;
  *)
        N=/etc/init.d/$SNAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
